version: '3'

services:
   meals_dishes_svr:
      build: ./meals_dishes_svr
      restart: always
      ports:
       - "5001:8000"
      depends_on:
       - mongo
   diet_svr:
      build: ./dietsvr
      restart: always
      ports:
       - "5002:8000"
      depends_on:
       - mongo
   mongo:
      image: mongo
      ports:
       - "27017:27017"
      volumes:
       - mongo_data:/data/db
   reverse:
      build: ./reverse
      ports:
       - "80:80"
      depends_on:
       - diet_svr
       - meals_dishes_svr

volumes:
 mongo_data: